### ISSUE TITLE
Sorting policies based on Status not working as expected

### ISSUE THREAD

**Issue by kostaspap** [panther-labs/panther#1240] opened 2020-07-27 13:45 UTC
### Describe the bug

Sorting the policies by `Status` doesn't seem to work as expected. 

### Steps to reproduce

1. Go to Policies page
2. Click on `Status` in order to sort policies by status
3. See that `Pass` and `Disabled` policies appear "mixed"  and not grouped together. 

### Expected behavior

`Disabled` policies are grouped together

### Environment

- Panther version or commit: ebc2c9620200931905193f5fc218cecee55b453e

### Screenshots

![Screen Shot 2020-07-27 at 4.36.17 PM.png](https://images.zenhubusercontent.com/5e4fc81c2009ef65e12fafd8/b9a5c752-e045-417b-a829-4f26bb5bdc45)

Note sure if it is a Frontend or Backend issue, maybe @austinbyers or @3nvi have more context on this.

**Comment by s0l0ist** [comment] 2020-07-27 15:44
It looks like we have two statuses: `PASS` or `FAIL`. Sorting is actually working in the backend and frontend; however, if the policy has been **disabled**, the frontend overwrites the status value with `DISABLED` instead. 

In its current state, it is possible to see `DISABLED` on passing or failed policies. In the screenshot posted, those two disabled policies have an underlying "passed" value that is being masked.

I think the problem is how we're presenting the data to the user while trying not to add clutter to the table. It also looks like we don't have the ability to sort or filter by enabled/disabled statuses either.

Just throwing around some solutions:
1.  Instead of a grey disabled badge we could have a binary-disabled badge that indicates the underlying pass/fail status (gray-green vs gray-red)
2. Create another column in the table with filtering/sorting capabilities for enabled/disabled

**Comment by austinbyers** [comment] 2020-07-27 15:45
Closing as a duplicate of #1179

**Closed by austinbyers** 2020-07-27 15:45 UTC
Labels: bug, p2
