### ISSUE TITLE
Disabled resources do not correctly sort by status

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#1179] opened 2020-07-16 00:02 UTC
### Describe the bug

Sorting resources by status does not work as expected. "Disabled" is mixed in with "Pass":

![Screen Shot 2020-07-15 at 4 59 03 PM](https://user-images.githubusercontent.com/3608925/87611428-e963bb00-c6bc-11ea-8125-8e7cff12f1bc.png)

This seems more likely a backend issue, so I've assigned it to myself for now

### Steps to reproduce

1. Deploy `master` branch
2. Go to Cloud Security > Policies
3. Sort by Status ascending
4. Note the "disabled" status mixed in with the passing status

### Expected behavior

"disabled" should be a separate status group in the sort

**Comment by 3nvi** [comment] 2020-07-16 08:54
Guessing that some additional param is missing on the payload, since that should be handled by the server.

We should also make sure that this is fixed in **all** rule & policy tables

**Comment by s0l0ist** [comment] 2020-07-27 15:48
It looks like we have two statuses: `PASS`, `FAIL`, or `ERROR`. Sorting is actually working in the backend and frontend; however, if the policy has been **disabled**, the frontend overwrites the status value with `DISABLED` instead. 

In its current state, it is possible to see `DISABLED` on passing, failed, or errored policies. In the screenshot posted, those two disabled policies have an underlying "passed" value that is being masked.

I think the problem is how we're presenting the data to the user while trying not to add clutter to the table. It also looks like we don't have the ability to sort or filter by enabled/disabled statuses either.

Just throwing around some solutions:
1.  Instead of a grey disabled badge we could have a binary-disabled badge that indicates the underlying pass/fail status (gray-green vs gray-red)
2. Create another column in the table with filtering/sorting capabilities for enabled/disabled

**Comment by austinbyers** [comment] 2020-07-27 16:59
> In its current state, it is possible to see DISABLED on passing, failed, or errored policies. In the screenshot posted, those two disabled policies have an underlying "passed" value that is being masked.

Ah, then would it be sufficient for the backend to sort by "enabled" status after sorting by pass/fail? Then at least they would be grouped together (pass: enabled, pass: disabled, fail: enabled, fail: disabled, error: enabled, error: disabled)

> Instead of a grey disabled badge we could have a binary-disabled badge that indicates the underlying pass/fail status (gray-green vs gray-red)

I agree, we need some way to show the underlying status - by design, the policy engine always evaluates resources against all applicable policies, even those which are disabled. Disabled policies will not trigger alerts nor remediations, but showing suppressed scan results is an important part of compliance reports.

> Create another column in the table with filtering/sorting capabilities for enabled/disabled

I agree with this as well, I could have sworn we actually used to have this. In any case, the backend already supports filtering and sorting by enabled/disabled

**Comment by 3nvi** [comment] 2020-08-03 08:34
> > In its current state, it is possible to see DISABLED on passing, failed, or errored policies. In the screenshot posted, those two disabled policies have an underlying "passed" value that is being masked.
> 
> Ah, then would it be sufficient for the backend to sort by "enabled" status after sorting by pass/fail? Then at least they would be grouped together (pass: enabled, pass: disabled, fail: enabled, fail: disabled, error: enabled, error: disabled)
> 
> > Instead of a grey disabled badge we could have a binary-disabled badge that indicates the underlying pass/fail status (gray-green vs gray-red)
> 
> I agree, we need some way to show the underlying status - by design, the policy engine always evaluates resources against all applicable policies, even those which are disabled. Disabled policies will not trigger alerts nor remediations, but showing suppressed scan results is an important part of compliance reports.
> 
> > Create another column in the table with filtering/sorting capabilities for enabled/disabled
> 
> I agree with this as well, I could have sworn we actually used to have this. In any case, the backend already supports filtering and sorting by enabled/disabled

Unfortunately, we can't keep columns wherever we want additional info displayed. We are limited by our UI, so perhaps the table is not a  proper UI to display this info.

We have a task to revamp the way the rules look and we'll switch our design to this https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/849670d3-62c0-462f-b399-bf6174c4352b/commits/latest/files/3cc6ad23-a286-4d07-a10b-a9852419c176/layers/2968E7EC-5DF5-4DC9-9532-5FC025FDE826?collectionId=e1ea6de7-39a9-46a1-9f20-a2fa3c7fa4be&collectionLayerId=eda90eb3-d696-4f6d-9fec-9e2c4d3e6d55.

Most likely, the same thing would apply to policies. In the meantime, knowing that adding a column is not an option, do we have alternatives?

**Comment by austinbyers** [comment] 2020-08-03 19:03
> In the meantime, knowing that adding a column is not an option

Why isn't that an option here? Having two columns: "enabled/disabled" and "pass/fail/error" makes a lot of sense to me.

If you must keep them to the same column, you could change the status column to combine them. Status becomes one of "pass", "fail", "error", "disabled-pass", "disabled-fail", or "disabled-error"

**Closed** 2020-08-27 17:34 UTC
Labels: bug, p2, team:web
