### ISSUE TITLE
Filter by multiple severity levels

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1068] opened 2020-06-22 21:30 UTC
### Describe the ideal solution

Currently, the user is able to filtering policies or rules by a severity level, but not by **multiple** severity levels.

### Describe your use cases

In some cases, it is useful to be able to view policies or rules by selecting multiply severity levels for increased productivity. The functionality should be similar to how the `Log Analysis` -> `Alerts` page allows for multiple severity level filtering.

### How frequently would you use such feature

Daily

### Describe alternatives you have considered

Applying a filter one at a time.

**Comment by austinbyers** [comment] 2020-11-17 18:16
Closing as a duplicate of #1997

**Closed by austinbyers** 2020-11-17 18:16 UTC
Labels: enhancement, p2, team:core infra
