### ISSUE TITLE
Add Log Analysis support for GCP p_ fields

### ISSUE THREAD

**Issue by wey-chiang** [panther-labs/panther#1579] opened 2020-09-22 14:15 UTC
### Describe the ideal solution

Currently, we have AWS specific `p_` fields that are incredibly useful, i.e. `p_any_aws_arns` and `p_any_account_ids`.
It would be cool to have some `p_` fields added to Log Analysis of GCP rules, i.e. `p_any_gcp_resource`, `p_any_gcp_service`, `p_any_gcp_project`, `p_any_gcp_bucket`, `p_any_gcp_method`, etc.

### Describe your use cases

These `p_` fields will be super useful for presenting clear and concise SummaryAttributes. It will also give end-users more flexibility when working with GCP resources.

### Describe alternatives you have considered

Currently, a lot of useful fields are nested in protoPayload. We could just find a way to flatten that field, however even if that were to be implemented, these `p_` fields would still be relevant & necessary for SummaryAttributes.

**Comment by kostaspap** [comment] 2020-09-22 14:19
Seems duplicate of https://github.com/panther-labs/panther/issues/801 ?

**Comment by rleighton** [comment] 2020-09-22 14:42
> #801

No, he is not asking to do a better job extracting into current `p_` fields, he is asking for new ones specific to GCP.

**Closed** 2021-02-18 17:17 UTC
Labels: enhancement, p2, team:data processing
