### ISSUE TITLE
Don't block log onboarding by link click

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#702] opened 2020-04-14 19:18 UTC
### Background

I've never stepped through the log onboarding flow before until today. I got stuck on the second step, even though I had already clicked the "launch stack" link and the stack was deployed. I couldn't figure out why the "next" button was still greyed out.

Turns out I clicked the link via a context menu instead of directly, a habit I never knew I had:

<img width="1240" alt="Screen Shot 2020-04-14 at 12 10 25 PM" src="https://user-images.githubusercontent.com/3608925/79264297-31b6d700-7e49-11ea-80c4-191004cc4f1d.png">

### Describe your ideal solution

Don't rely on a link clink to activate the next button, or at least make it more obvious how to proceed. Ideas:

* Never grey out the "next" button - add text like "When the stack has finished deploying, click the next button"
* Add a "stack is deployed" checkbox which will allow the user to explicitly activate the button

**Comment by 3nvi** [comment] 2020-04-15 12:18
Duplicate of #598 . Please feel free to write there

**Closed by 3nvi** 2020-04-15 12:18 UTC
Labels: enhancement, frontend
