### ISSUE TITLE
Do not log user input validation errors

### ISSUE THREAD

**Issue by giorgosp** [panther-labs/panther#2342] opened 2021-01-05 10:00 UTC
### Describe the bug

Saw this error in the error logs in a customer's deployment:

`AlertID invalid, failed to satisfy the condition: hexadecimal` happening in the `GetAlert` and `GenerateAlertSummaries` operations.

This is the commit that added the hexadecimal validation https://github.com/panther-labs/panther/commit/b8ef7c74f39da6387b45d1d4052c150cb9b4ccb2

### Steps to reproduce

Ping me if you want link to the logs

### Expected behavior

No error

### Environment

- Panther version: 1.14.3

**Comment by kostaspap** [comment] 2021-01-05 10:43
@giorgosp have you seen this issue many times or is it one-off? This check has been there since almost a year (the date of the referenced commit is 12 March 2020) so it's not a new thing.
Since the AlertID is a URL parameter, if someone enters the wrong URL, this error might appear

**Comment by giorgosp** [comment] 2021-01-05 10:49
Saw several occasions and then it stopped. It happened in both the `GetAlert` and `GenerateAlertSummaries` operations. 
I am not very familiar with that part of the system though.

**Comment by kostaspap** [comment] 2021-01-05 11:32
It's true, I saw it recently as well. I think it was because of wrong AlertID provided by user in the input. 
I think this issue is safe to close unless it is possible that this could be caused by Policy Alerts? @s0l0ist

**Comment by s0l0ist** [comment] 2021-01-11 17:33
Policy Alerts are also hex (MD5 hash). I am not sure about Rule Error alerts, however.

**Comment by kostaspap** [comment] 2021-01-12 09:56
> Policy Alerts are also hex (MD5 hash). I am not sure about Rule Error alerts, however.

They are as well - they use the same logic as rule matches.

**Comment by kostaspap** [comment] 2021-01-12 09:56
Resolving - it seems that this was caused due to invalid user input.

**Comment by giorgosp** [comment] 2021-01-12 11:22
Perhaps we shouldn't log the error then?

**Comment by kostaspap** [comment] 2021-01-12 11:28
> Perhaps we shouldn't log the error then?

This error is logged by our lambda router afaik.... I was thinking that this should be out once we refactor the API but that's a bigger effort.... I am thinking we could achieve what you suggest rather easily: update [this code](https://github.com/panther-labs/panther/blob/master/pkg/genericapi/router.go#L77-L79) so that if it is a Validation error to just log a warning or sth. Thoughts? @giorgosp

**Comment by giorgosp** [comment] 2021-01-12 11:45
Yeah good idea. I haven't seen many error logs from user input so it's not high prio. I think we should keep it open though.

**Closed** 2021-02-19 16:31 UTC
Labels: bug, p1, team:data processing
